### PR TITLE
Fix height prop to work with rem

### LINKED ISSUE #346: `height` prop doesn't work if theme text sizes use `rem`
When grommet theme defines text sizes as `rem`, the `height` prop on an icon doesn't work properly. No vertical padding is added.

Example theme with "px" based text sizes: Notice alignment of icon in notification matches the first line of text
Screenshot 2024-12-11 at 11 43 40 AM

Example theme with "rem" based text sizes: Icon is not aligned with first line of text
Screenshot 2024-12-11 at 11 43 33 AM

### PR DESCRIPTION
**Pull request by taysea**
Closes #346. If unit is `rem`, when we parseMetricToNum we need to multiply by 16 to appropriately calculate padding.

Tested locally in storybook and added unit test.

Screenshot 2024-12-11 at 12 11 55 PM
Screenshot 2024-12-11 at 12 11 47 PM

```
import React from 'react';
import { boolean, text } from '@storybook/addon-knobs';

import { ThemeProvider } from 'styled-components';
import { Box, Text, Grommet } from 'grommet';
import * as Icons from './icons';

const customTheme = {
  global: {
    colors: {
      icon: '#2196f3',
      attention: '#ff3333',
    },
  },
  icon: {
    size: {
      small: '12px',
      medium: '18px',
      large: '48px',
      xlarge: '300px',
    },
  },
  text: {
    small: {
      size: '0.75rem',
      height: '0.875rem',
    },
    medium: {
      size: '1.125rem',
      height: '1.5rem',
    },
  },
};

export default {
  title: 'Icon',
};

export const Default = () => {
  const Icon = Icons[text('Icon', 'Accessibility')];
  if (!Icon) {
    return null;
  }
  return <Icon />;
};

export const Color = () => {
  const Icon = Icons[text('Icon', 'Accessibility')];
  if (!Icon) {
    return null;
  }
  const theme = JSON.parse(JSON.stringify(customTheme));
  theme.icon.disableScaleDown = boolean('disableScaleDown', false);
  return (
    <ThemeProvider theme={theme}>
      <Icon size={text('Size', 'xlarge')} color={text('Color', 'attention')} />
    </ThemeProvider>
  );
};

export const Plain = () => <Icons.Pocket color="plain" />;

export const CustomTheme = () => {
  const Icon = Icons[text('Icon', 'Accessibility')];
  if (!Icon) {
    return null;
  }
  const theme = JSON.parse(JSON.stringify(customTheme));
  theme.icon.disableScaleDown = boolean('disableScaleDown', false);
  return (
    <Grommet theme={theme}>
      <Box direction="row">
        <Icon size={text('Size', 'medium')} height="medium" />
        <Text>Here is some text I want my icon to align with.</Text>
      </Box>
    </Grommet>
  );
};
```

### CODE REVIEW

File: src/js/utils.js [hunk 1]
```diff
@@ -57,7 +57,9 @@ export function iconPad(props) {
 
   let style = '';
   if (height && theme?.text?.[height]?.height) {
-    const lineHeight = parseMetricToNum(theme.text[height].height);
+    const unit = theme.text[height].height.match(/[a-z]+$/)?.[0] || 'px';
```
Comment (halocline) [inline src/js/utils.js:60]: Why do we need both the regex and the `||` for px? I would think the regex would match both `rem` and `px` -- also I would think this would match any a-z chars such as `em`,`ft`, even `zebra`.

Should we make the regex a bit more targeted to the specific units which are valid/we support?

File: src/js/utils.js [hunk 2]
```diff
@@ -57,7 +57,9 @@ export function iconPad(props) {
...
+    const lineHeight =
+      parseMetricToNum(theme.text[height].height) * (unit === 'rem' ? 16 : 1);
```
Comment (halocline) [inline src/js/utils.js:62]: Where does the 16 come from? Assuming this assumes and 16px root? Can we document this with a comment and/or a static variable (e.g. `const ROOT_UNIT = 16`)?

File: src/js/utils.js (hunk 1 above)
Comment (taysea) [reply src/js/utils.js]: Made adjustments in latest commit.

File: src/js/utils.js [hunk 3]
```diff
@@ -57,7 +57,16 @@ export function iconPad(props) {
...
   if (height && theme?.text?.[height]?.height) {
-    const lineHeight = parseMetricToNum(theme.text[height].height);
+    // browser default is 16px, but accommodate if app has modified
+    // include fallback in case window is undefined
+    const rootFontSize = parseMetricToNum(
+      window?.getComputedStyle(document.body).getPropertyValue('font-size') ||
+        '16px',
+    );
+    // the unit on theme text
+    const unit = theme.text[height].height.match(/[a-z]+$/)?.[0];
```
Comment (halocline) [inline src/js/utils.js:67]: I think the following would only match what we want as well. Can we give that a quick try?

```suggestion
    const unit = theme.text[height].height.match(/(px|rem)/);
```
